# This workflow will deploy your app to Railway 
# Note: Railway can do this automatically but it's just an examble of CI/CD 
name: Deploy to Railway

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Docker to Railway
        run: railway up --service=nestSimpleAuth --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



